[package]
name = "snake_game"
version = "0.1.0"
authors = ["justincremer <jacremer@live.com>"]
edition = "2018"

[dependencies]
ggez = { git = "https://github.com/ggez/ggez", branch = "master" }
glam = { version = "0.12", features = ["mint"]}
